// Generated by apply_support_config.py. Do not edit directly.
export const supportConfig = {
  company_name: "CraftMatch",
  domain_name: "craftmatch.com",
  support_email: "support@craftmatch.com",
  escalation_email: "craftmatch.assist@gmail.com",
  effective_date: "2026-06-06",
  last_updated: "2026-06-06",
  office_address: "University of Ghana, Legon Campus, Accra, Ghana",
  team_members: [
  {
    "name": "Peniel",
    "role": "Database & Supabase Engineer",
    "desc": "Maintains storage, row-level security, and realtime syncing."
  },
  {
    "name": "Kwabena",
    "role": "Express API Developer",
    "desc": "Owns backend server controllers, auth validation, and catalog logic."
  },
  {
    "name": "Nhyira",
    "role": "Flutter Mobile Developer",
    "desc": "Designs customer & worker app layouts, and maps notifications."
  }
]
};
